// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Lajule/dac/ent/schema"
	"github.com/Lajule/dac/ent/training"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	trainingFields := schema.Training{}.Fields()
	_ = trainingFields
	// trainingDescCreatedAt is the schema descriptor for created_at field.
	trainingDescCreatedAt := trainingFields[0].Descriptor()
	// training.DefaultCreatedAt holds the default value on creation for the created_at field.
	training.DefaultCreatedAt = trainingDescCreatedAt.Default.(func() time.Time)
	// trainingDescWords is the schema descriptor for words field.
	trainingDescWords := trainingFields[1].Descriptor()
	// training.DefaultWords holds the default value on creation for the words field.
	training.DefaultWords = trainingDescWords.Default.(int)
}
