// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Lajule/dac/ent/schema"
	"github.com/Lajule/dac/ent/training"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	trainingFields := schema.Training{}.Fields()
	_ = trainingFields
	// trainingDescCreatedAt is the schema descriptor for created_at field.
	trainingDescCreatedAt := trainingFields[0].Descriptor()
	// training.DefaultCreatedAt holds the default value on creation for the created_at field.
	training.DefaultCreatedAt = trainingDescCreatedAt.Default.(func() time.Time)
	// trainingDescDuration is the schema descriptor for duration field.
	trainingDescDuration := trainingFields[1].Descriptor()
	// training.DefaultDuration holds the default value on creation for the duration field.
	training.DefaultDuration = trainingDescDuration.Default.(int)
	// trainingDescClosable is the schema descriptor for closable field.
	trainingDescClosable := trainingFields[2].Descriptor()
	// training.DefaultClosable holds the default value on creation for the closable field.
	training.DefaultClosable = trainingDescClosable.Default.(bool)
	// trainingDescStopwatch is the schema descriptor for stopwatch field.
	trainingDescStopwatch := trainingFields[3].Descriptor()
	// training.DefaultStopwatch holds the default value on creation for the stopwatch field.
	training.DefaultStopwatch = trainingDescStopwatch.Default.(int)
	// trainingDescProgress is the schema descriptor for progress field.
	trainingDescProgress := trainingFields[4].Descriptor()
	// training.DefaultProgress holds the default value on creation for the progress field.
	training.DefaultProgress = trainingDescProgress.Default.(int)
	// trainingDescAccuracy is the schema descriptor for accuracy field.
	trainingDescAccuracy := trainingFields[5].Descriptor()
	// training.DefaultAccuracy holds the default value on creation for the accuracy field.
	training.DefaultAccuracy = trainingDescAccuracy.Default.(int)
	// trainingDescSpeed is the schema descriptor for speed field.
	trainingDescSpeed := trainingFields[6].Descriptor()
	// training.DefaultSpeed holds the default value on creation for the speed field.
	training.DefaultSpeed = trainingDescSpeed.Default.(int)
}
