// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lajule/dac/ent/predicate"
	"github.com/Lajule/dac/ent/training"
)

// TrainingUpdate is the builder for updating Training entities.
type TrainingUpdate struct {
	config
	hooks    []Hook
	mutation *TrainingMutation
}

// Where appends a list predicates to the TrainingUpdate builder.
func (tu *TrainingUpdate) Where(ps ...predicate.Training) *TrainingUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetDuration sets the "duration" field.
func (tu *TrainingUpdate) SetDuration(i int) *TrainingUpdate {
	tu.mutation.ResetDuration()
	tu.mutation.SetDuration(i)
	return tu
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (tu *TrainingUpdate) SetNillableDuration(i *int) *TrainingUpdate {
	if i != nil {
		tu.SetDuration(*i)
	}
	return tu
}

// AddDuration adds i to the "duration" field.
func (tu *TrainingUpdate) AddDuration(i int) *TrainingUpdate {
	tu.mutation.AddDuration(i)
	return tu
}

// SetTotalDuration sets the "total_duration" field.
func (tu *TrainingUpdate) SetTotalDuration(i int) *TrainingUpdate {
	tu.mutation.ResetTotalDuration()
	tu.mutation.SetTotalDuration(i)
	return tu
}

// SetNillableTotalDuration sets the "total_duration" field if the given value is not nil.
func (tu *TrainingUpdate) SetNillableTotalDuration(i *int) *TrainingUpdate {
	if i != nil {
		tu.SetTotalDuration(*i)
	}
	return tu
}

// AddTotalDuration adds i to the "total_duration" field.
func (tu *TrainingUpdate) AddTotalDuration(i int) *TrainingUpdate {
	tu.mutation.AddTotalDuration(i)
	return tu
}

// SetTextLength sets the "text_length" field.
func (tu *TrainingUpdate) SetTextLength(i int) *TrainingUpdate {
	tu.mutation.ResetTextLength()
	tu.mutation.SetTextLength(i)
	return tu
}

// SetNillableTextLength sets the "text_length" field if the given value is not nil.
func (tu *TrainingUpdate) SetNillableTextLength(i *int) *TrainingUpdate {
	if i != nil {
		tu.SetTextLength(*i)
	}
	return tu
}

// AddTextLength adds i to the "text_length" field.
func (tu *TrainingUpdate) AddTextLength(i int) *TrainingUpdate {
	tu.mutation.AddTextLength(i)
	return tu
}

// SetInputsLength sets the "inputs_length" field.
func (tu *TrainingUpdate) SetInputsLength(i int) *TrainingUpdate {
	tu.mutation.ResetInputsLength()
	tu.mutation.SetInputsLength(i)
	return tu
}

// SetNillableInputsLength sets the "inputs_length" field if the given value is not nil.
func (tu *TrainingUpdate) SetNillableInputsLength(i *int) *TrainingUpdate {
	if i != nil {
		tu.SetInputsLength(*i)
	}
	return tu
}

// AddInputsLength adds i to the "inputs_length" field.
func (tu *TrainingUpdate) AddInputsLength(i int) *TrainingUpdate {
	tu.mutation.AddInputsLength(i)
	return tu
}

// SetAccuracy sets the "accuracy" field.
func (tu *TrainingUpdate) SetAccuracy(i int) *TrainingUpdate {
	tu.mutation.ResetAccuracy()
	tu.mutation.SetAccuracy(i)
	return tu
}

// SetNillableAccuracy sets the "accuracy" field if the given value is not nil.
func (tu *TrainingUpdate) SetNillableAccuracy(i *int) *TrainingUpdate {
	if i != nil {
		tu.SetAccuracy(*i)
	}
	return tu
}

// AddAccuracy adds i to the "accuracy" field.
func (tu *TrainingUpdate) AddAccuracy(i int) *TrainingUpdate {
	tu.mutation.AddAccuracy(i)
	return tu
}

// SetSpeed sets the "speed" field.
func (tu *TrainingUpdate) SetSpeed(i int) *TrainingUpdate {
	tu.mutation.ResetSpeed()
	tu.mutation.SetSpeed(i)
	return tu
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (tu *TrainingUpdate) SetNillableSpeed(i *int) *TrainingUpdate {
	if i != nil {
		tu.SetSpeed(*i)
	}
	return tu
}

// AddSpeed adds i to the "speed" field.
func (tu *TrainingUpdate) AddSpeed(i int) *TrainingUpdate {
	tu.mutation.AddSpeed(i)
	return tu
}

// Mutation returns the TrainingMutation object of the builder.
func (tu *TrainingUpdate) Mutation() *TrainingMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TrainingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TrainingUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TrainingUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TrainingUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TrainingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(training.Table, training.Columns, sqlgraph.NewFieldSpec(training.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Duration(); ok {
		_spec.SetField(training.FieldDuration, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedDuration(); ok {
		_spec.AddField(training.FieldDuration, field.TypeInt, value)
	}
	if value, ok := tu.mutation.TotalDuration(); ok {
		_spec.SetField(training.FieldTotalDuration, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedTotalDuration(); ok {
		_spec.AddField(training.FieldTotalDuration, field.TypeInt, value)
	}
	if value, ok := tu.mutation.TextLength(); ok {
		_spec.SetField(training.FieldTextLength, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedTextLength(); ok {
		_spec.AddField(training.FieldTextLength, field.TypeInt, value)
	}
	if value, ok := tu.mutation.InputsLength(); ok {
		_spec.SetField(training.FieldInputsLength, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedInputsLength(); ok {
		_spec.AddField(training.FieldInputsLength, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Accuracy(); ok {
		_spec.SetField(training.FieldAccuracy, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedAccuracy(); ok {
		_spec.AddField(training.FieldAccuracy, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Speed(); ok {
		_spec.SetField(training.FieldSpeed, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedSpeed(); ok {
		_spec.AddField(training.FieldSpeed, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{training.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TrainingUpdateOne is the builder for updating a single Training entity.
type TrainingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrainingMutation
}

// SetDuration sets the "duration" field.
func (tuo *TrainingUpdateOne) SetDuration(i int) *TrainingUpdateOne {
	tuo.mutation.ResetDuration()
	tuo.mutation.SetDuration(i)
	return tuo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (tuo *TrainingUpdateOne) SetNillableDuration(i *int) *TrainingUpdateOne {
	if i != nil {
		tuo.SetDuration(*i)
	}
	return tuo
}

// AddDuration adds i to the "duration" field.
func (tuo *TrainingUpdateOne) AddDuration(i int) *TrainingUpdateOne {
	tuo.mutation.AddDuration(i)
	return tuo
}

// SetTotalDuration sets the "total_duration" field.
func (tuo *TrainingUpdateOne) SetTotalDuration(i int) *TrainingUpdateOne {
	tuo.mutation.ResetTotalDuration()
	tuo.mutation.SetTotalDuration(i)
	return tuo
}

// SetNillableTotalDuration sets the "total_duration" field if the given value is not nil.
func (tuo *TrainingUpdateOne) SetNillableTotalDuration(i *int) *TrainingUpdateOne {
	if i != nil {
		tuo.SetTotalDuration(*i)
	}
	return tuo
}

// AddTotalDuration adds i to the "total_duration" field.
func (tuo *TrainingUpdateOne) AddTotalDuration(i int) *TrainingUpdateOne {
	tuo.mutation.AddTotalDuration(i)
	return tuo
}

// SetTextLength sets the "text_length" field.
func (tuo *TrainingUpdateOne) SetTextLength(i int) *TrainingUpdateOne {
	tuo.mutation.ResetTextLength()
	tuo.mutation.SetTextLength(i)
	return tuo
}

// SetNillableTextLength sets the "text_length" field if the given value is not nil.
func (tuo *TrainingUpdateOne) SetNillableTextLength(i *int) *TrainingUpdateOne {
	if i != nil {
		tuo.SetTextLength(*i)
	}
	return tuo
}

// AddTextLength adds i to the "text_length" field.
func (tuo *TrainingUpdateOne) AddTextLength(i int) *TrainingUpdateOne {
	tuo.mutation.AddTextLength(i)
	return tuo
}

// SetInputsLength sets the "inputs_length" field.
func (tuo *TrainingUpdateOne) SetInputsLength(i int) *TrainingUpdateOne {
	tuo.mutation.ResetInputsLength()
	tuo.mutation.SetInputsLength(i)
	return tuo
}

// SetNillableInputsLength sets the "inputs_length" field if the given value is not nil.
func (tuo *TrainingUpdateOne) SetNillableInputsLength(i *int) *TrainingUpdateOne {
	if i != nil {
		tuo.SetInputsLength(*i)
	}
	return tuo
}

// AddInputsLength adds i to the "inputs_length" field.
func (tuo *TrainingUpdateOne) AddInputsLength(i int) *TrainingUpdateOne {
	tuo.mutation.AddInputsLength(i)
	return tuo
}

// SetAccuracy sets the "accuracy" field.
func (tuo *TrainingUpdateOne) SetAccuracy(i int) *TrainingUpdateOne {
	tuo.mutation.ResetAccuracy()
	tuo.mutation.SetAccuracy(i)
	return tuo
}

// SetNillableAccuracy sets the "accuracy" field if the given value is not nil.
func (tuo *TrainingUpdateOne) SetNillableAccuracy(i *int) *TrainingUpdateOne {
	if i != nil {
		tuo.SetAccuracy(*i)
	}
	return tuo
}

// AddAccuracy adds i to the "accuracy" field.
func (tuo *TrainingUpdateOne) AddAccuracy(i int) *TrainingUpdateOne {
	tuo.mutation.AddAccuracy(i)
	return tuo
}

// SetSpeed sets the "speed" field.
func (tuo *TrainingUpdateOne) SetSpeed(i int) *TrainingUpdateOne {
	tuo.mutation.ResetSpeed()
	tuo.mutation.SetSpeed(i)
	return tuo
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (tuo *TrainingUpdateOne) SetNillableSpeed(i *int) *TrainingUpdateOne {
	if i != nil {
		tuo.SetSpeed(*i)
	}
	return tuo
}

// AddSpeed adds i to the "speed" field.
func (tuo *TrainingUpdateOne) AddSpeed(i int) *TrainingUpdateOne {
	tuo.mutation.AddSpeed(i)
	return tuo
}

// Mutation returns the TrainingMutation object of the builder.
func (tuo *TrainingUpdateOne) Mutation() *TrainingMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TrainingUpdate builder.
func (tuo *TrainingUpdateOne) Where(ps ...predicate.Training) *TrainingUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TrainingUpdateOne) Select(field string, fields ...string) *TrainingUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Training entity.
func (tuo *TrainingUpdateOne) Save(ctx context.Context) (*Training, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TrainingUpdateOne) SaveX(ctx context.Context) *Training {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TrainingUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TrainingUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TrainingUpdateOne) sqlSave(ctx context.Context) (_node *Training, err error) {
	_spec := sqlgraph.NewUpdateSpec(training.Table, training.Columns, sqlgraph.NewFieldSpec(training.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Training.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, training.FieldID)
		for _, f := range fields {
			if !training.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != training.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Duration(); ok {
		_spec.SetField(training.FieldDuration, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedDuration(); ok {
		_spec.AddField(training.FieldDuration, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.TotalDuration(); ok {
		_spec.SetField(training.FieldTotalDuration, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedTotalDuration(); ok {
		_spec.AddField(training.FieldTotalDuration, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.TextLength(); ok {
		_spec.SetField(training.FieldTextLength, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedTextLength(); ok {
		_spec.AddField(training.FieldTextLength, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.InputsLength(); ok {
		_spec.SetField(training.FieldInputsLength, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedInputsLength(); ok {
		_spec.AddField(training.FieldInputsLength, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Accuracy(); ok {
		_spec.SetField(training.FieldAccuracy, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedAccuracy(); ok {
		_spec.AddField(training.FieldAccuracy, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Speed(); ok {
		_spec.SetField(training.FieldSpeed, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedSpeed(); ok {
		_spec.AddField(training.FieldSpeed, field.TypeInt, value)
	}
	_node = &Training{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{training.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
