// Code generated by ent, DO NOT EDIT.

package training

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the training type in the database.
	Label = "training"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldWords holds the string denoting the words field in the database.
	FieldWords = "words"
	// Table holds the table name of the training in the database.
	Table = "trainings"
)

// Columns holds all SQL columns for training fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldWords,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultWords holds the default value on creation for the "words" field.
	DefaultWords int
)

// OrderOption defines the ordering options for the Training queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByWords orders the results by the words field.
func ByWords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWords, opts...).ToFunc()
}
